# Generated by Django 4.1.4 on 2023-01-19 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='grade',
            field=models.CharField(max_length=100),
        ),
    ]
