# Generated by Django 4.1.4 on 2023-03-04 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_details_grade'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.RemoveField(
            model_name='details',
            name='grade',
        ),
        migrations.AddField(
            model_name='details',
            name='absent',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='details',
            name='course',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='details',
            name='date',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='details',
            name='froms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='details',
            name='leaveletter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='details',
            name='medical',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='details',
            name='previlege',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='details',
            name='reason',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='details',
            name='relation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='details',
            name='rno',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='details',
            name='section',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='details',
            name='tos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='details',
            name='tot',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='details',
            name='totdays',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='details',
            name='ug',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='details',
            name='username',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='details',
            name='year',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='details',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
